[username]
length = 6
# number of characters to use in generation

prefix = ""
# string to be added to front of username

suffix = ""
# string to be added to end of username

characters = ["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z"]
# characters to be randomly picked from

[misc]
mode = 2
# 1 = generate random using settings above
# 2 = try every line of tocheck.txt as a name

type = 2
# 1 = player usernames
# 2 = group names

time_between_checks = 0.1
# time between api requests in seconds