[username]
characters = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"]
length = 6
prefix = ""
suffix = ""

[misc]
mode = 1
type = 1
time_between_checks = 0.1
